
[maid_storage_manager]

	[maid_storage_manager.craft]
		enable = true

	[maid_storage_manager.smithing]
		enable = true

	[maid_storage_manager.furnace]
		enable = true

	[maid_storage_manager.stone_cutting]
		enable = true

	[maid_storage_manager.altar]
		enable = true

	[maid_storage_manager.brewing]
		enable = true
		count = 3

	[maid_storage_manager.watering]
		enable = true
		bucket = true
		bottle = true

	[maid_storage_manager.stripping]
		enable = true

	[maid_storage_manager.tacz]
		enable = true

[create]

	[create.pressing]
		enable = true

	[create.compacting]
		enable = true

	[create.mixing]
		enable = true

	[create.milling]
		enable = true

	[create.crushing]
		enable = true
		count = 16

	[create.fan]
		enable = true
		count = 8
		splashing = true
		haunting = true
		smoking = true
		blasting = true
		replace_furnace = true

	[create.item_application]
		enable = true

	[create.deploying]
		enable = true

[maidsoulkitchen_youkaishomecoming]

	[maidsoulkitchen_youkaishomecoming.moka_pot]
		enable = true

	[maidsoulkitchen_youkaishomecoming.kettle]
		enable = true

	[maidsoulkitchen_youkaishomecoming.drying_rack]
		enable = true
		count = 4

	[maidsoulkitchen_youkaishomecoming.cuisine]
		enable = true

	[maidsoulkitchen_youkaishomecoming.basin]
		enable = true

[maidsoulkitchen_farmersdelight]

	[maidsoulkitchen_farmersdelight.campfire_cooking]
		enable = true

	[maidsoulkitchen_farmersdelight.skillet]
		enable = true

	[maidsoulkitchen_farmersdelight.campfire_cooking_from_hand]
		enable = true

	[maidsoulkitchen_farmersdelight.cutting]
		enable = true

	[maidsoulkitchen_farmersdelight.cooking]
		enable = true

[maidsoulkitchen_maidsoulkitchen]

	[maidsoulkitchen_maidsoulkitchen.consume_water_from_single]
		enable = true

	[maidsoulkitchen_maidsoulkitchen.consume_water_from_multi]
		enable = true

	[maidsoulkitchen_maidsoulkitchen.item_use]
		enable = true

