// priority: 500

registerItemMaidBauble("fast:charge")
registerItemTag("fast:charge", "fast:magic")
registerItemMaidBauble("fast:overcharged_mana_flask")
registerItemTag("fast:overcharged_mana_flask", "fast:magic")
registerItemMaidBauble("irons_spellbooks:fire_upgrade_orb")
registerItemTag("irons_spellbooks:fire_upgrade_orb", "fast:magic")
registerItemMaidBauble("irons_spellbooks:nature_upgrade_orb")
registerItemTag("irons_spellbooks:nature_upgrade_orb", "fast:magic")
registerItemMaidBauble("irons_spellbooks:lightning_upgrade_orb")
registerItemTag("irons_spellbooks:lightning_upgrade_orb", "fast:magic")
registerItemMaidBauble("irons_spellbooks:evocation_upgrade_orb")
registerItemTag("irons_spellbooks:evocation_upgrade_orb", "fast:magic")
registerItemMaidBauble("irons_spellbooks:holy_upgrade_orb")
registerItemTag("irons_spellbooks:holy_upgrade_orb", "fast:magic")
registerItemMaidBauble("irons_spellbooks:ender_upgrade_orb")
registerItemTag("irons_spellbooks:ender_upgrade_orb", "fast:magic")
registerItemMaidBauble("irons_spellbooks:blood_upgrade_orb")
registerItemTag("irons_spellbooks:blood_upgrade_orb", "fast:magic")
registerItemMaidBauble("irons_spellbooks:ice_upgrade_orb")
registerItemTag("irons_spellbooks:ice_upgrade_orb", "fast:magic")